import {
    defineConfig,
    presetIcons,
    presetWind,
    UserConfig,
    transformerDirectives,
    presetUno,
    //@ts-ignore (we symlink this file to places where it IS installed)
} from 'unocss'

const config = {
    presets: [presetUno({
        dark: 'media',
    }), presetWind(), presetIcons()],
    shortcuts: [
        {
            'flex-center': 'flex justify-center items-center',
            'flex-col-center': 'flex flex-col justify-center items-center',
        },
    ],
    rules: [],
    theme: {
        colors: {
            black: '#111111',
            stone: '#353534',
            grey2: '#2a2a3f',
            white: '#f6f6f6',
            neon: '#dcff71',
            blue: '#004fff',
            orange: '#dd6e42',
            magenta: '#bf1363',
            transparent: 'transparent',
        },
        font: {
            sans: [
                'Barlow',
                'ui-sans-serif',
                'system-ui',
                '-apple-system',
                'BlinkMacSystemFont',
                '"Segoe UI"',
                'Roboto',
                '"Helvetica Neue"',
                'Arial',
                '"Noto Sans"',
                'sans-serif',
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
                '"Segoe UI Symbol"',
                '"Noto Color Emoji"',
            ],
            serif: [
                'ui-serif',
                'Georgia',
                'Cambria',
                '"Times New Roman"',
                'Times',
                'serif',
            ],
            mono: [
                'ui-monospace',
                'SFMono-Regular',
                'Menlo',
                'Monaco',
                'Consolas',
                '"Liberation Mono"',
                '"Courier New"',
                'monospace',
            ],
            heading: [
                'OpenSans',
                'ui-sans-serif',
                'system-ui',
                '-apple-system',
                'BlinkMacSystemFont',
                '"Segoe UI"',
                'Roboto',
                '"Helvetica Neue"',
                'Arial',
                '"Noto Sans"',
                'sans-serif',
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
                '"Segoe UI Symbol"',
                '"Noto Color Emoji"',
            ],
            display: [
                'Futura',
                'ui-sans-serif',
                'system-ui',
                '-apple-system',
                'BlinkMacSystemFont',
                '"Segoe UI"',
                'Roboto',
                '"Helvetica Neue"',
                'Arial',
                '"Noto Sans"',
                'sans-serif',
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
                '"Segoe UI Symbol"',
                '"Noto Color Emoji"',
            ],
        },
    },
    transformers: [transformerDirectives()],
}

export default defineConfig(config) as UserConfig<(typeof config)['theme']>
