[package]
name = "globe"
version = "0.1.0"
edition = "2021"

[features]
simulation-mode = []

[dependencies]
kinode_process_lib = { git = "https://github.com/kinode-dao/process_lib", rev = "6ed0cda" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5.0"
wit-bindgen = "0.24.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "kinode:process"
