[package]
name = "hyperwallet"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
alloy-primitives = "0.7"
alloy-sol-types = "0.7"
anyhow = "1.0"
base64ct = "=1.6.0"
chrono = { version = "0.4", features = ["serde"] }
hyperware_process_lib = { path = "../../../../../process_lib", features = ["hyperwallet", "logging"] }
#hyperware_process_lib = { git = "https://github.com/hyperware-ai/process_lib", branch = "hyperwallet-client_lib", features = ["hyperwallet", "logging"] }
process_macros = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5"
wit-bindgen = "0.36.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "hyperware:process"
