[package]
name = "set-nodes"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
hyperware_process_lib = { git = "https://github.com/hyperware-ai/process_lib", rev = "6597ae1" }
process_macros = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wit-bindgen = "0.42.1"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "hyperware:process"
