[package]
name = "peers"
version = "0.1.0"
edition = "2021"

[features]
simulation-mode = []

[dependencies]
kinode_process_lib = "0.9.1"
rmp-serde = "1.1.2"
serde = { version = "1.0", features = ["derive"] }
wit-bindgen = "0.24.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "kinode:process"
