[workspace]
resolver = "2"
members = [
    "add-provider",
    "alias",
    "cat",
    "echo",
    "get-providers",
    "help",
    "hfetch",
    "hi",
    "kill",
    "m",
    "net-diagnostics",
    "peer",
    "peers",
    "remove-provider",
    "terminal",
    "top",
]

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
