[package]
name = "app_store"
version = "0.3.0"
edition = "2021"

[features]
simulation-mode = []

[dependencies]
alloy-primitives = "0.6.2"
alloy-sol-types = "0.6.2"
anyhow = "1.0"
bincode = "1.3.3"
kinode_process_lib = { git = "https://github.com/kinode-dao/process_lib", tag = "v0.6.0" }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.8"
sha3 = "0.10.8"
url = "2.4.1"
urlencoding = "2.1.0"
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "21a46c7" }
zip = { version = "0.6.6", default-features = false }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "kinode:process"
