[package]
name = "hyperware-parse-wit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
wit-parser = { version = "0.220.0", features = ["serde"] }
zip = { version = "2.2", default-features = false }
