[workspace]
resolver = "2"
members = [
    "app_store",
    "chain",
    "download",
    "downloads",
    "ft_worker",
    "install",
    "uninstall",
]

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
